### PR TITLE
data_structure.md New model proposal

### PR DESCRIPTION
**Pull request by davelab6**
:)

### CODE REVIEW

**Comment by davelab6** [comment]
The `Features` needs adobe feature file compiler in JS, which doesn't exist, but the fontTools python feaLib could be ported once it is finished later this year.

**Comment by davelab6** [comment]
but for the most simple things I think the existing Ligature JS code can be used, right?

**Comment by mattlag** [comment]
Do you have a link or something where I can read more about "Features"?  I'm not even sure what they are or how they work :-) 

V1 had very simple ligatures... basically just specify a few code points, and we'd replace them with a single glyph.  And, seeing as how OpenType.js doesn't support Ligatures (Or Kerning) we never really had a chance to see how they functioned in a real .otf font.

They work in SVG Fonts, though :-D

**Comment by mattlag** [comment]
I know there are many forms of substitution that the GSUB table can specify... for Glyphr Studio, we'd probably start with traditional ligature behavior.  I'm reading this at the moment:
https://www.microsoft.com/typography/otspec/gsub.htm#LS

**Comment by davelab6** [comment]
That's the primary thing to read, along with
http://www.adobe.com/devnet/opentype/afdko/topic_feature_file_syntax.html
which is what I expect in font sources

**Comment by mattlag** [comment]
Ah, this is perfect!  Thanks!

**Pull request merged**
